### ISSUE TITLE
Roadmap 0.1.0-0.3.0

### ISSUE THREAD

**Issue by BERENZ** [ncn-foreigners/nonprobsvy#1]
The initial version of the package should have:

## Version 0.1.0

1. Mass imputation -- families: `gaussian`, `binomial`, `Gamma`, `inverse.gaussian`, `poisson`, `quasi*` and `MASS::negative.binomial`. 
- [ ] Estimator: using model based approach (`stats::glm` and `MASS::glm.nb`)
- [ ] Estimator: using predictive mean matching (`RANN::nn2`)
- [ ] Variance estimator:  Kim et al. (2021), p. 950.

Literature:
- Kim, J. K., Park, S., Chen, Y., & Wu, C. (2021). Combining non-probability and probability survey samples through mass imputation. Journal of the Royal Statistical Society. Series A: Statistics in Society, 184(3), 941–963. https://doi.org/10.1111/rssa.12696

## Version 0.2.0

2. Propensity score - `binomial()` with `logit`, `probit` and `cloglog` links
- [ ] unit-level survey data is available
- [ ] only population totals are available

Literature:
- Chen, Y., Li, P., & Wu, C. (2020). Doubly Robust Inference With Nonprobability Survey Samples. Journal of the American Statistical Association, 115(532), 2011–2021. https://doi.org/10.1080/01621459.2019.1677241

## Version 0.3.0

3. Doubly robust  
- [ ] standard : Chen, Li and Wu (2020)
- [ ] with minimization of asymptotic bias: Yang, Kim and Rui (2020)

Literature:

- Chen, Y., Li, P., & Wu, C. (2020). Doubly Robust Inference With Nonprobability Survey Samples. Journal of the American Statistical Association, 115(532), 2011–2021. https://doi.org/10.1080/01621459.2019.1677241
- Kim, J. K., & Wang, Z. (2018). Sampling Techniques for Big Data Analysis. International Statistical Review, 1, 1–15. https://doi.org/10.1111/insr.12290
- Yang, S., Kim, J. K., & Rui, S. (2020). Doubly robust inference when combining probability and non-probability samples with high dimensional. Journal of the Royal Statistical Society. Series B: Statistical Methodology, 82(2), 445–465. https://doi.org/10.1111/rssb.12354

**Comment by BERENZ** [comment]
Closed because of #6
