### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LukaszChrostowski** [ncn-foreigners/nonprobsvy#11]
Issues to consider for the current version of the package.

To develop (SHORT TERM):

- [x] add `pop_totals` / `pop_means` for variable selection method
- [x] add the rest of the estimation methods `gee` / `mle` provided after variable selection 
- [x] provide bias minimization method to the base usage of the package
- [x] accelerate performance for variable selection algorithm written in C++
- [x] structural changes, such as equal `model.frame` call for all models and one function for models with and without variable selection
- [x] Ability to call functions for several outcome variables e.g. `y1 + y2 + ... + yk ~ x1 + x2 + x3 + ... + xn`
- [x] add trace/verbose tracking for variable selection and bootstrap algorithms
- [x] move bias correction definition to the other `control` function or consider another way to define it
- [x] change functions name in `OutcomeMethods`
- [x] fix `BIC.nonprobsvy` in `summary`
- [x] change the structure of defining `gee` with h functions in `control_selection`
- [x] add `error` message in case of duplicates of outcome variables in formula
- [x] add `error` message in case of badly defined formulas
- [ ] add propensity score adjustment using `xgboost` model.
- [ ] add `svrep` (bootstrap weighting) to the functionality of the package.
- [ ] add `div` to variable selection models

To develop (LONG TERM):

- [ ] variance for DR estimator when MI estimation using NN algorithm
- [ ] method to estimate mean/median/totals in subsets/groups (called on the `nonprobsvy` object).
- [x] variance for MI estimator when MI using PMM imputation

To fix:

- [ ] `weights` for non-probability sample - not stable algorithm during estimation (overestimation of propensity weights or errors in `maxLik` model)
- [ ] variance for DR and MI estimator (with NN)

**Comment by Kertoo** [comment]
> add propensity score adjustment using xgboost model.

Fitting more complicated machine learning models (such as `xgboost `) is more involved than just calling `lm/glm` with avoiding overfitting etc. and adding a plethora of minor tweaks.  Maybe it would just be better to create a method where user supplies a fitted ML `object` instead of calling `xgboost` internally? This would make tuning the model much less tedious.

**Comment by LukaszChrostowski** [comment]
tasks moved to https://github.com/ncn-foreigners/nonprobsvy/issues/47
