### ISSUE TITLE
nonprobsvy v0.2.0 - roadmap

### ISSUE THREAD

**Issue by LukaszChrostowski** [ncn-foreigners/nonprobsvy#47]
Issues to add/consider for the next version of the package:

- [ ] add propensity score adjustment using `xgboost` model.
- [ ] add `svrep` (`bootstrap` weighting) to the functionality of the package.
- [x] add div to variable selection models (seperate variable selection for ipw and mi model)
- [ ] variance for `DR` and `MI` estimator (when `NN` method for mass imputation)
- [x] method to estimate mean/median/totals in subsets/groups (called on the `nonprobsvy` object).
- [ ] add calibration for quantiles (see https://github.com/ncn-foreigners/nonprobsvy/issues/36).
- [ ] add empirical likelihood for ipw estimation (see https://github.com/ncn-foreigners/nonprobsvy/issues/20).
- [ ] improve variable selection for `pop_totals`.
- [ ] add estimation methods for overlapping samples (see https://academic.oup.com/jssam/article/11/5/1181/6960643).
- [ ] variables randomization when selection algorithm
- [x] fix the following display in summary when variable selection
<img width="875" alt="Screenshot 2024-09-15 at 10 23 11" src="https://github.com/user-attachments/assets/f86ebc0e-9f75-46aa-b0da-aba9c01f0ad0">
